version: '3.5'
services:

  measurement-neo4j:
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
#      - "./dockerimports/:/data"
      - "./dockerimports/:/var/lib/neo4j/import"

# initial creds after container build:
# user: neo4j
# pwd: neo4j

# local user: neo4j
# local password: neo4jTri4lPa55w0rd