services:
  remotemodel-open-webui:
    privileged: true
    build:
      context: ..
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: remotemodel-open-webui
    volumes:
      - remotemodel-open-webui:/app/backend/data
    ports:
      - 3000:8080
    environment:
#     for usage with localhost just comment out the OLLAMA_BASE_URL
#      - 'OLLAMA_BASE_URL=http://193.149.37.198:11434'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_AUTH=False'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  remotemodel-open-webui: {}